// <auto-generated />
using System;
using DataAccesLayer.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccesLayer.Migrations
{
    [DbContext(typeof(EstateDbContext))]
    [Migration("20231002212039_mig-1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(5157),
                            Name = "Satılık",
                            Status = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(5167),
                            Name = "Kiralık",
                            Status = 1
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Budget")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstateTypeId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EstateTypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Adress = "Ankara",
                            Budget = 5000000,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(5293),
                            LastName = "Baler",
                            Mail = "semihbaler@gmail.com",
                            Name = "Semih",
                            Status = 1,
                            TypeId = 2
                        },
                        new
                        {
                            CustomerId = 2,
                            Adress = "Balıkesir",
                            Budget = 12000,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(5299),
                            LastName = "Baler",
                            Name = "Merve",
                            Status = 1,
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Estate", b =>
                {
                    b.Property<int>("EstateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstateId"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstateTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EstateId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EstateTypeId");

                    b.ToTable("Estates");

                    b.HasData(
                        new
                        {
                            EstateId = 1,
                            Adress = "Bağlıca",
                            CategoryId = 1,
                            City = "Ankara",
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(5348),
                            District = "Etimesgut",
                            EstateTypeId = 2,
                            Price = 7500000,
                            Status = 1
                        },
                        new
                        {
                            EstateId = 2,
                            Adress = "Alacaatlı",
                            CategoryId = 1,
                            City = "Ankara",
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(5350),
                            District = "Çankaya",
                            EstateTypeId = 3,
                            Price = 12000000,
                            Status = 1
                        },
                        new
                        {
                            EstateId = 3,
                            Adress = "Burhaniye",
                            CategoryId = 2,
                            City = "Balıkesir",
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(5352),
                            District = "Susurluk",
                            EstateTypeId = 1,
                            Price = 6500,
                            Status = 1
                        },
                        new
                        {
                            EstateId = 4,
                            Adress = "Elvan",
                            CategoryId = 1,
                            City = "İzmir",
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(5352),
                            District = "merkez",
                            EstateTypeId = 1,
                            Price = 1500000,
                            Status = 1
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.EstateType", b =>
                {
                    b.Property<int>("EstateTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstateTypeId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EstateTypeId");

                    b.ToTable("EstateType");

                    b.HasData(
                        new
                        {
                            EstateTypeId = 1,
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(5400),
                            Name = "Müstakil",
                            Status = 1
                        },
                        new
                        {
                            EstateTypeId = 2,
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(6912),
                            Name = "Daire",
                            Status = 1
                        },
                        new
                        {
                            EstateTypeId = 3,
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(6915),
                            Name = "Arsa",
                            Status = 1
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(7016),
                            Name = "Ahmet",
                            Role = "User",
                            Status = 1
                        },
                        new
                        {
                            UserId = 2,
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(7017),
                            Name = "Mehmet",
                            Role = "Customer",
                            Status = 1
                        },
                        new
                        {
                            UserId = 3,
                            CreatedDate = new DateTime(2023, 10, 3, 0, 20, 38, 987, DateTimeKind.Local).AddTicks(7018),
                            Name = "Yade",
                            Role = "Admin",
                            Status = 1
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Customer", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Category", "Category")
                        .WithMany("Customers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.EstateType", null)
                        .WithMany("Customers")
                        .HasForeignKey("EstateTypeId");

                    b.HasOne("EntityLayer.Concrete.User", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Estate", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Category", "Category")
                        .WithMany("Estates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.EstateType", "Type")
                        .WithMany("Estates")
                        .HasForeignKey("EstateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Estates");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EstateType", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Estates");
                });
#pragma warning restore 612, 618
        }
    }
}
